language: generic

# Ubuntu 16.04
dist: xenial

env:
  global:
    - LUAROCKS_VERSION=3.1.2
    - VIPS_VERSION=8.8.0
    - VIPS_WARNING=0
    - TEST_COVERAGE=1
    - JOBS=`nproc`
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
    - PATH=$HOME/vips/bin:$HOME/luarocks/bin:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin:$PATH

cache:
  directories:
    - $HOME/vips
    - $HOME/luarocks

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://openresty.org/package/ubuntu $(lsb_release -cs) main'
        key_url: 'https://openresty.org/package/pubkey.gpg'
      # use imagemagick 6.9.7-4 instead than 6.8.9-9
      - sourceline: 'ppa:opencpu/imagemagick'
      # add support for HEIF files
      - sourceline: 'ppa:strukturag/libheif'
      - sourceline: 'ppa:strukturag/libde265'
    packages:
      - openresty
      - openresty-resty
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
      - libtiff5-dev
      - libheif-dev
      # missing on xenial, unfortunately
      # - libwebpmux2
      - libglib2.0-dev

before_install:
  # add support for WebP
  - wget http://archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebp-dev_0.6.1-2_amd64.deb
  - wget http://archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebpdemux2_0.6.1-2_amd64.deb
  - wget http://archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebpmux3_0.6.1-2_amd64.deb
  - wget http://archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebp6_0.6.1-2_amd64.deb
  - sudo dpkg -i *.deb
  - |
    bash .ci/install-vips.sh \
      --skip-cache \
      --disable-dependency-tracking
  - |
    bash .ci/install-luarocks.sh \
      --with-lua=/usr/local/openresty/luajit/ \
      --lua-suffix=jit-2.1.0-beta3 \
      --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
  - eval `luarocks path`

install:
  - cp app/config.example.lua app/config.lua
  - make dev

script:
  - .ci/run_tests.sh

after_success:
  - luacov-coveralls
